### ISSUE TITLE
Quick Start

### ISSUE THREAD

**Issue by urwithajit9** [Di-Chai/FedEval#2]
Hi Chai,
Thank you for sharing the FedEval, it is really going to be very useful in evaluating and comparing the FL approaches. 
I followed the Quickstart from documents and successfully build and run the system. But the dashboard is not showing the result (screenshot
![dashboard](https://user-images.githubusercontent.com/2667549/117862788-04e42600-b2ce-11eb-9349-9c70795e71a1.png)
 attached).
I have doubts about the required dataset, do we need to download the dataset mentioned in the documents? or when we create the clients, does it get the dataset?
Thanks and Regards.

**Comment by Di-Chai** [comment]
Thanks for trying our evaluation system.

Question 1: do we need to download the dataset mentioned in the documents?

Answer: If you followed the quickstart, then the MNIST, Cifar10, Cifar100 datasets should already  be available. And the other datasets, e.g., FEMNIST, CelebA, need to download and manually put into path: FedEval/data. I'll put a download link for these datasets afterwards.

Question 2: when we create the clients, does it get the dataset?

Answer: Yes, each client will automatically load the dataset. If the data file cannot be found, the clients will exit with an error.

According to your dashboard, there's no client online. Could you help to provide the following information, so we can find the problem?

1. Which dataset you are using?
2. Provide the logs of the exited clients. Through : ```sudo docker logs client1 > client1.log```" Or, you can also run the trial again by: ```sudo docker-compose up```, then you should be able to see the error.

**Comment by urwithajit9** [comment]
Hi 
Thanks for the response.
I am not making any changes in 1_data_config.yml and didn't find any option to choose a dataset so I think the quickstart example would be running with default configurations (with selected dataset). 

Yes, I followed the quick start instructions (attached the screenshot). the `sudo docker-compose up` is showing warnings for each client and HTTP 400 error from the server. the log is coming blank.

Note: 
1) somewhere in doc I read that sudo should be run without a password but I am running sudo with a password, does it create any issue?
2) In docker-compose.yml, I see client_0 volumes: has a path 
/FL-experiment/FedEval-master:/FML 
but I didn't see any folder being created as /FML , is this also an issue?

server      | 172.18.0.12 - - [12/May/2021 03:55:35] "GET /socket.io/?EIO=3&transport=polling&t=1620791735062-0 HTTP/1.1" 400 -
server      | 172.18.0.3 - - [12/May/2021 03:55:35] "GET /socket.io/?EIO=3&transport=polling&t=1620791735129-0 HTTP/1.1" 400 -
server      | 172.18.0.5 - - [12/May/2021 03:55:35] "GET /socket.io/?EIO=3&transport=polling&t=1620791735130-0 HTTP/1.1" 400 -
server      | 172.18.0.11 - - [12/May/2021 03:55:35] "GET /socket.io/?EIO=3&transport=polling&t=1620791735256-0 HTTP/1.1" 400 -
server      | 172.18.0.8 - - [12/May/2021 03:55:35] "GET /socket.io/?EIO=3&transport=polling&t=1620791735257-0 HTTP/1.1" 400 -
server      | 172.18.0.7 - - [12/May/2021 03:55:35] "GET /socket.io/?EIO=3&transport=polling&t=1620791735290-0 HTTP/1.1" 400 -
server      | 172.18.0.9 - - [12/May/2021 03:55:35] "GET /socket.io/?EIO=3&transport=polling&t=1620791735404-0 HTTP/1.1" 400 -
server      | 172.18.0.6 - - [12/May/2021 03:55:35] "GET /socket.io/?EIO=3&transport=polling&t=1620791735508-0 HTTP/1.1" 400 -
server      | 172.18.0.2 - - [12/May/2021 03:55:35] "GET /socket.io/?EIO=3&transport=polling&t=1620791735775-0 HTTP/1.1" 400 -
server      | 172.18.0.4 - - [12/May/2021 03:55:35] "GET /socket.io/?EIO=3&transport=polling&t=1620791735855-0 HTTP/1.1" 400 -


Uploading Kazam_screencast_00021.mp4…

**Comment by urwithajit9** [comment]
screen recording for the quick-start

https://user-images.githubusercontent.com/2667549/117916706-9d0bfa80-b322-11eb-8f9a-8f4999d2a9e1.mp4

**Comment by Di-Chai** [comment]
Hi, 

server | 172.18.0.12 - - [12/May/2021 03:55:35] "GET /socket.io/?EIO=3&transport=polling&t=1620791735062-0 HTTP/1.1" 400 -

The above 400 error might be caused by the wrong package version. I have updated the Dockerfile ( https://github.com/Di-Chai/FedEval/blob/master/docker/Dockerfile ), can you rebuild the docker image and try again?

Also:

(1) Running sudo with a password will bring problems. So please guarantee that sudo can be executed without requiring the password. 

(2) This is not an issue, because /FML is a path used inside the container. Thus no dir is created outside.

In the screen recording, client1's log should be saved to client1.log, can you show this file as well?

**Comment by urwithajit9** [comment]
Hi Di-Chai,

Thank you so much. Now, I got it working. I think the main issue was with the package version as you mentioned. Now, it working with a fresh install and making the sudo run without a password.
